export const FETCH_STATUSES_REQUEST = "FETCH_STATUSES_REQUEST";
export const FETCH_STATUSES_SUCCESS = "FETCH_STATUSES_SUCCESS";
export const FETCH_STATUSES_FAILURE = "FETCH_STATUSES_FAILURE";

export const FETCH_STATUS_BY_ID_REQUEST = "FETCH_STATUS_BY_ID_REQUEST";
export const FETCH_STATUS_BY_ID_SUCCESS = "FETCH_STATUS_BY_ID_SUCCESS";
export const FETCH_STATUS_BY_ID_FAILURE = "FETCH_STATUS_BY_ID_FAILURE";

export const ADD_STATUS_REQUEST = "ADD_STATUS_REQUEST";
export const ADD_STATUS_SUCCESS = "ADD_STATUS_SUCCESS";
export const ADD_STATUS_FAILURE = "ADD_STATUS_FAILURE";

export const UPDATE_STATUS_REQUEST = "UPDATE_STATUS_REQUEST";
export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS";
export const UPDATE_STATUS_FAILURE = "UPDATE_STATUS_FAILURE";

export const DELETE_STATUS_REQUEST = "DELETE_STATUS_REQUEST";
export const DELETE_STATUS_SUCCESS = "DELETE_STATUS_SUCCESS";
export const DELETE_STATUS_FAILURE = "DELETE_STATUS_FAILURE";
