export const FETCH_ASSIGNMENTS_REQUEST = "FETCH_ASSIGNMENTS_REQUEST";
export const FETCH_ASSIGNMENTS_SUCCESS = "FETCH_ASSIGNMENTS_SUCCESS";
export const FETCH_ASSIGNMENTS_FAILURE = "FETCH_ASSIGNMENTS_FAILURE";

export const ADD_ASSIGNMENT_REQUEST = "ADD_ASSIGNMENT_REQUEST";
export const ADD_ASSIGNMENT_SUCCESS = "ADD_ASSIGNMENT_SUCCESS";
export const ADD_ASSIGNMENT_FAILURE = "ADD_ASSIGNMENT_FAILURE";

export const DELETE_ASSIGNMENT_REQUEST = "DELETE_ASSIGNMENT_REQUEST";
export const DELETE_ASSIGNMENT_SUCCESS = "DELETE_ASSIGNMENT_SUCCESS";
export const DELETE_ASSIGNMENT_FAILURE = "DELETE_ASSIGNMENT_FAILURE";

export const FETCH_ASSIGNMENT_BY_ID_REQUEST = "FETCH_ASSIGNMENT_BY_ID_REQUEST";
export const FETCH_ASSIGNMENT_BY_ID_SUCCESS = "FETCH_ASSIGNMENT_BY_ID_SUCCESS";
export const FETCH_ASSIGNMENT_BY_ID_FAILURE = "FETCH_ASSIGNMENT_BY_ID_FAILURE";

export const UPDATE_ASSIGNMENT_REQUEST = "UPDATE_ASSIGNMENT_REQUEST";
export const UPDATE_ASSIGNMENT_SUCCESS = "UPDATE_ASSIGNMENT_SUCCESS";
export const UPDATE_ASSIGNMENT_FAILURE = "UPDATE_ASSIGNMENT_FAILURE";
